### ISSUE TITLE
remove " from your code and examples

### ISSUE THREAD

**Issue by kentonbmax** [manishrasrani/microsoft-applicationinsights-angular5#1]
JS standard is to use single quotes.

**Comment by manishrasrani** [comment]
@kentonbmax - Well this is debatable with each having its say! 
From typescript devs themselves--[TypeScript Github issue #5811](https://github.com/Microsoft/TypeScript/issues/5811#issuecomment-160187924): "But to specifically answer your question, we occasionally work in languages other than TypeScript. All those languages either require double quotes for strings (e.g. C#, C++, F#) or at least allow double quotes for strings (e.g. Python, Ruby). It's easier not to ask people to shift their muscle memory when switching back and forth between languages."
